import type { GasConnectionTableColumnConfig } from '@/types/Settings';

/**
 * Domyślna konfiguracja wszystkich kolumn tabeli GasConnections
 */
export function getDefaultTableColumns(): GasConnectionTableColumnConfig[] {
  let order = 0;

  return [
    // Adres
    {
      field: 'address.commune',
      header: 'Gmina',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'address.city',
      header: 'Miasto',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'address.street',
      header: 'Ulica',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'taskNo',
      header: 'Nr zadania',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'conditionNo',
      header: 'Nr warunków',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'contractNo',
      header: 'Nr umowy',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'contractDate',
      header: 'Data umowy',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'wsgFinalPickupDate',
      header: 'Termin odb. tech.',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'designer',
      header: 'Projektant',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'coordinator',
      header: 'Koordynator',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'endCustomer',
      header: 'Klient',
      visible: true,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'customer',
      header: 'Zleceniodawca',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },

    // Zakres prac
    {
      field: 'workRangeGasConnections',
      header: 'Zakres',
      visible: false,
      order: order++,
      frozen: false,
      sortable: false,
      filterable: true,
    },
    {
      field: 'workRangeGasStations',
      header: 'Stacja',
      visible: false,
      order: order++,
      frozen: false,
      sortable: false,
      filterable: true,
    },
    {
      field: 'workRangeConnection',
      header: 'Włączenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: false,
      filterable: true,
    },
    // Podstawowe dane zadania
    {
      field: 'conditionDate',
      header: 'Data warunków',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasDistribution',
      header: 'Rozdzielnia',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'connectionAgreementNumber',
      header: 'Umowa przył.',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'sapUpNo',
      header: 'SAP/UP',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'accelerationDate',
      header: 'Data przyspieszenia',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'taskValue',
      header: 'Wartość zadania',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'finishDeadline',
      header: 'Termin odb. końcowego',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'projectDeadline',
      header: 'Termin projektu',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'projectValue',
      header: 'Wartość projektu',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },

    {
      field: 'constructionValue',
      header: 'Wartość wykonawstwa',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'isPGN',
      header: 'PGN',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'phase',
      header: 'Etap',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    // gasConnectionDesign - Stage 1
    {
      field: 'gasConnectionDesign.projectOrderSubmissionDate',
      header: 'Zlecenie projektu - złożenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.projectOrderConfirmationDate',
      header: 'Zlecenie projektu - potwierdzenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.proxySubmissionDate',
      header: 'Pełnomocnictwo - złożenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.proxyReceiptDate',
      header: 'Pełnomocnictwo - otrzymanie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.mapSubmissionDate',
      header: 'Mapa - złożenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.mapReceiptDate',
      header: 'Mapa - otrzymanie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.extractSubmissionDate',
      header: 'Wypis - złożenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.extractReceiptDate',
      header: 'Wypis - otrzymanie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    // gasConnectionDesign - Stage 2
    {
      field: 'gasConnectionDesign.zudpSubmissionDate',
      header: 'ZUDP - złożenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.zudpReceiptDate',
      header: 'ZUDP - otrzymanie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.utilityCompanyType',
      header: 'Zakład',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.utilityCompanySubmissionDate',
      header: 'Zakład - złożenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.utilityCompanyReceiptDate',
      header: 'Zakład - otrzymanie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    // gasConnectionDesign - Stage 3
    {
      field: 'gasConnectionDesign.wsgAgreementSubmissionDate',
      header: 'Uzgodnienie WSG - złożenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.wsgAgreementReceiptDate',
      header: 'Uzgodnienie WSG - otrzymanie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.wsgAgreementAgreementDate',
      header: 'Uzgodnienie WSG - uzgodnienie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.wsgAgreementNo',
      header: 'Nr uzgodnienie WSG',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.wsgAgreementPointSchemeSubmissionDate',
      header: 'Uzg schematu punktu w WSG - złożenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.wsgAgreementPointSchemeReceiptDate',
      header: 'Uzg schematu punktu w WSG - otrzymanie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    // gasConnectionDesign - Stage 4
    {
      field: 'gasConnectionDesign.trafficOrganizationProjectSubmissionDate',
      header: 'Proj org ruchu - złożenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.trafficOrganizationProjectReceiptDate',
      header: 'Proj org ruchu - otrzymanie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.designerTraffic',
      header: 'Proj org ruchu - projektant',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.gasPointOrderDate',
      header: 'Punkt gazowy - zamówienie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.gasPointPickupDate',
      header: 'Punkt gazowy - odb punktu',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.gasPointDocPickupDate',
      header: 'Punkt gazowy - odb dok',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionDesign.zudpSentToSurveyorDate',
      header: 'ZUDP - wysłano geodecie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    // gasConnectionBuild
    {
      field: 'gasConnectionBuild.substationNotificationSubmissionDate',
      header: 'Zawiadomienie rodzielni',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionBuild.surveyingSketchesDate',
      header: 'Geodezja - szkice',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionBuild.surveyingInventoryDate',
      header: 'Geodezja - inwentaryzacja',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionBuild.realizationStartDate',
      header: 'Realizacja - rozpoczęcie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionBuild.realizationEndDate',
      header: 'Realizacja - zakończenie',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionBuild.wsgTechnicalAcceptanceDate',
      header: 'WSG - odbiór tech.',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionBuild.wsgFinalAcceptanceSubmissionDate',
      header: 'WSG - odb koń wysłany',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionBuild.wsgFinalAcceptanceDate',
      header: 'WSG - odbiór końcowy',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionBuild.technicalAcceptanceProtocolNo',
      header: 'Nr protokołu odb tech',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
    {
      field: 'gasConnectionBuild.gasPipelineInventoryNumber',
      header: 'Nr inw gazociągu',
      visible: false,
      order: order++,
      frozen: false,
      sortable: true,
      filterable: true,
    },
  ];
}
